export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGIN_OUTIL";
export const AUTHORIZED_SUCCESS = "AUTHORIZED_SUCCESS";
export const AUTHORIZED_FAIL = "AUTHORIZED_FAIL";
